### ISSUE TITLE
When opening the graph view it defaults to 0,0 which is most of the time empty

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/VSCodeExtension#15]
**What is the current behavior?**

When opening the graph view it defaults to 0,0 which is most of the time empty.
So it just looks like you are in this weird void or something has broken.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Create a new Yarn file in VSCode and add in a node
2. Click the show graph button
3. Behold the empty graph

**What is the expected behavior?**

I should be centered on the new node I created, or if opening a file with lots of nodes at least centered on one of them.
I just should never open on empty space, if I want to scroll to empty space so be it.

**Please tell us about your environment:**

  - Extension Version: 2.2.15

**Other information**

**Comment by desplesda** [comment]
Fixed in 73f2132d3414d9df8f25649888b93ecaf125681a.
