### ISSUE TITLE
Nodes without position information start out all on top of each other

### ISSUE THREAD

**Issue by TheMartianLife** [YarnSpinnerTool/VSCodeExtension#16]
**What is the current behavior?**

If you have a Yarn script with multiple nodes that was made out of editor (e.g., in Try Yarn Spinner) and thus has no `position` property in the node headers, each node has a default inferred position of 0,0. This means that opening the graph view for the first time shows what looks like a single node (the last node) and nothing else—all other nodes will be hidden underneath it.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

* Make a script:
* 
```
title: Start
---
<<jump NodeA>>
===
title: NodeA
---
This is a node.
```

* Open graph view in VS Code.

* Observe that only one node is visible.

**What is the expected behavior?**

All nodes are visible, even if their positions are somewhat random or need adjusting.

**Environment**

  - VS Code Version: 1.68.1
  - Extension Version: 2.2.15

**Suggested fix** 

For each node detected in the file, the default is `position: 0,n` where `n` is the 100 * index of the node. 

More complicated but potentially nicer options are some sort of grid, or nodes sorted for directional flow.

**Comment by TheMartianLife** [comment]
For consistency's sake, if this is changed it might also be worth making it so that opening the graph view also adds 

```
position: 0,0
```

to the first node, given it will now be adding something to every other node.

**Comment by desplesda** [comment]
It occurs to me that the current behaviour (nodes without a position header default to `(0,0)`) might be modified slightly to reveal overlapping nodes by doing this: given a constant value `offset` and counter `count`, for each node without a position header, default its position to `(offset * count, offset * count)`, then increment `count`. This would cause nodes to appear to stack up.

**Comment by desplesda** [comment]
New in 9067f929e9a3661ac99f8f75ceaefdc365dfc0b9: if multiple nodes have no `position` header, then they'll be stacked up.

<img width="603" alt="Screen Shot 2022-10-27 at 3 36 46 pm" src="https://user-images.githubusercontent.com/901768/198192544-04dd2511-97f6-4621-aed5-08e7c4d88763.png">
