### ISSUE TITLE
Exception when trying to run the new Dialogue Preview feature

### ISSUE THREAD

**Issue by loofou** [YarnSpinnerTool/VSCodeExtension#17]
**What is the current behavior?**

When trying to run the new Dialogue Preview feature on any yarn file from our game, VSCode simply shows an error message with exception.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Create most minimalistic yarn file possible: Just a Start node with a single line.
2. Run "Yarn Spinner: Preview Dialogue"
3. See exception

**What is the expected behavior?**

Get the preview feature (I honestly don't know how it looks like).

**Please tell us about your environment:**

  - Extension Version: v2.2.36
  - VSCode Version: v1.69.2

**Other information** 

I'm not sure where to get the full log, but the part of the exception that VSCode shows me is as below:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2287749/179999971-262f0e39-9688-4e54-bd62-534fc358ac9e.png">

**Comment by DX5536** [comment]
![Code_2022-07-21_00-36-48](https://user-images.githubusercontent.com/49788345/180094228-9248f23f-cb9d-4428-b1fc-a054571d21c8.png)

I got the same error. I used an existing Yarn file of a game I have completed, so no duplicated node name/syntax error etc. is present.

**Comment by desplesda** [comment]
Fixed in YarnSpinnerTool/YarnSpinner@d8dba6f4762f09cedae412e1d565fb1b039384cf. The fix will be included in the next release of the extension. Thank you for the report!
