### ISSUE TITLE
Dialogue Preview needs to be closed and reopened to display saved edits.

### ISSUE THREAD

**Issue by doppelreal** [YarnSpinnerTool/VSCodeExtension#21]
**What is the current behavior?**

Restarting the Dialogue Preview does not display newly saved files. Only yarn files as they were when starting the Dialogue Preview.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

- Create a Yarn file
- Start Dialogue Preview and leave it open
- Edit the Yarn File and save the edits.
- Jump back to the Dialogue Preview.

**What is the expected behavior?**

This might be as designed! Closing and reopening the Dialogue Preview displays the saved edits as expected.

The restart button should load the saved edits, if possible.

**Please tell us about your environment:**

MacOs

  - Yarn Spinner Version: 2.x
  - Extension Version: 2.2.40
  - Visual Studio Code: 1.69.2

**Comment by desplesda** [comment]
Fixed in cc8f3d3b724da8f7e3ba98cecf754bb9461268ad.

**Comment by desplesda** [comment]
Whoops! Wrongly closed this one.

**Comment by desplesda** [comment]
This is currently working as designed. The Dialogue Preview works by compiling your project and then running it; subsequent edits won't appear. (It might be cool to automatically update or re-run your code, but that's a feature for another day!)
