### ISSUE TITLE
Calling multiple variables in dialogue displays them from high to low instead of correct variable.

### ISSUE THREAD

**Issue by doppelreal** [YarnSpinnerTool/VSCodeExtension#24]
**What is the current behavior?**

Calling multiple variables within a dialogue line will display them incorrectly.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Declare three integers (named $number1, $number2, $number3) and assign the values 1, 2 and 3 according to the names.

Call the variables in a dialogue line like this: 
This is {$number1}, that is {$number2} and over here {$number3}.

Instead of calling the correct variables, it will display: 
This is 3, that is 2 and over here 1.

**What is the expected behavior?**

Integers to be called correctly.

**Please tell us about your environment:**

  - Yarn Spinner Version: 2.x 
  - Extension Version: 2.2.40
  - Unity Version: n/a

**Comment by desplesda** [comment]
Confirmed existing in the extension. Will investigate!

**Comment by McJones** [comment]
fixed in https://github.com/YarnSpinnerTool/YarnSpinner-TypeScript/commit/513f77a27930263070fbf6662987cabcf25c07eb, will be reflected in a future update to the extension soon.
