### ISSUE TITLE
Broken links in README /  extension description

### ISSUE THREAD

**Issue by dogboydog** [YarnSpinnerTool/VSCodeExtension#34]
The README which also displays on the marketplace has some broken links in this section: 

If you want to import command and function definitions for a language other than C#, or you want to override information that the language server parses from C#, add a JSON file with the extension ".ysls.json" to your project's folder using the [ysls.json schema](https://github.com/YarnSpinnerTool/LanguageServer/blob/main/LanguageServer/src/Server/Documentation/ysls.schema.json).

For examples, take a look at this [import example](https://github.com/YarnSpinnerTool/LanguageServer/blob/main/LanguageServer/ImportExample.ysls.json) or the [yarn spinner built in Commands and Functions file](https://github.com/YarnSpinnerTool/LanguageServer/blob/main/LanguageServer/src/Server/Documentation/BuiltInFunctionsAndCommands.ysls.json).

**Comment by Bryan-Legend** [comment]
https://github.com/YarnSpinnerTool/YarnSpinner/blob/main/YarnSpinner.LanguageServer/src/Server/Documentation/BuiltInFunctionsAndCommands.ysls.json

**Comment by dogboydog** [comment]
Yup, I have opened a PR a few days ago which fixes this link among others

**Comment by Bryan-Legend** [comment]
> Yup, I have opened a PR a few days ago which fixes this link among others

Thanks. I just had to dig the link out of the commit so I figured I'd dump it there.

I'm not getting any of this command data to load. Is it working for you?

I opened an issue about it at: https://github.com/YarnSpinnerTool/YarnSpinner/issues/361
