### ISSUE TITLE
Yarn Spinner Visual Studio Code Extension Graph View Is Broken

### ISSUE THREAD

**Issue by KesKim** [YarnSpinnerTool/VSCodeExtension#40]
**What is the current behavior?**

Visual Studio Code extension is installed and I open a file TestScript, then press "Show Graph". The Graph displays empty, "Jump to Node" lists no nodes, and pressing "Add Node" gives this error pop-up:

"Can't add node: file:///d:/<REDACTED>/YarnProjects/TestScript.yarn is not a part of any project"
I have omitted a part of the file path above, it does print accurately to match my project location.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

- Set Visual Studio Code as Unity's code editor via "Preferences/External Tools" and browsing to your VS Code exe path
- Create a new .yarn file via Unity Editor's Project View and "Create"-context menu "Yarn Spinner/New Yarn Script"
- create a new Yarn Project via the Inspector button displayed when viewing your new yarn file
- Use Unity's Inspector in Debug mode (top-right triple-dot "..." of the Inspector window and select "Debug" mode to see internal values) to confirm your yarn file is listed in the project as found by the lookup path set in the project
- Open the yarn file in Visual Studio Code
- copy-paste the below contents into the yarn file:

```
title: Start
---
A: Hello! It's me, World!
B: Hi, World!
-> Punch World
	Ouch!
-> Hug World
	Awwh! <3
===
```

- Press "Show Graph" in Visual Studio Code and check "Jump to Node" list, empty graph view and try pressing "Add Node" button.

**What is the expected behavior?**

Based on [documentation](https://docs.yarnspinner.dev/getting-started/editing-with-vs-code/writing-yarn-in-vs-code) the VS Code extension should just work; no specific installation or Yarn project setup steps are ever mentioned for it.

**Please tell us about your environment:**

- Windows version: Windows 11 Home / 22H2 (OS Build 22621.1992)
- Yarn Spinner version: 2.3.1
- Unity version: 2023.1.3f1
- Visual Studio Code version: 1.80.1
- Yarn Spinner Extension version: 2.2.106

**Comment by RyanMakesMovies** [comment]
I'm getting the same error. 

- Win 10 Home
- Yarn Spinner 2.3.1
- Unity 2022.3.4f1
- VS Code 1.81.1
- Yarn Spinner Extension 2.2.119

**Comment by boermansjo** [comment]
Have you tried using the Pre-Release Version in Visual Studio Code ?

- Yarn Spinner Extension 2.2.123
- VS Code 1.81.1

The example provided works using that version.

**Comment by RyanMakesMovies** [comment]
@boermansjo That got it working for me. Thanks!

**Comment by boermansjo** [comment]
@RyanMakesMovies Glad it is working. This is a nice tool but sadly not the right one for me. I need something similar but with a json export.

**Comment by desplesda** [comment]
This fix will land in an upcoming release of Yarn Spinner for Visual Studio Code. Thanks for the report!

**Comment by Agasper** [comment]
Any workaround for this ? It still doesn't work even for pre-release version 3.0.340 
* MacOs 
* VSCode 1.99.3
