### ISSUE TITLE
[Show Graph] command 'yarnspinner.show-graph' not found

### ISSUE THREAD

**Issue by yoyo201626** [YarnSpinnerTool/VSCodeExtension#43]
**What is the current behavior?**
My vscode notify “command 'yarnspinner.show-graph' not found”  when I click “Show Grash”.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. open yarn file
```yarn
Wow!
My first ever Yarn script in Unity!

-> Gosh!
-> Incredible!
-> I'm amazed!

Anyway, time to get writing!
===
```
2. Click “Show Graph” and then the error happened
![image](https://github.com/YarnSpinnerTool/VSCodeExtension/assets/104079404/6666b41a-8142-4ebe-8fc7-d09d977ffd9c)

**What is the expected behavior?**
I want the graph to be displayed when I click "Show Graph"

**Please tell us about your environment:**

  - Extension Version:  v2.2.128

**Other information** 
I find vscode is downling  .net, does it matter?
![image](https://github.com/YarnSpinnerTool/VSCodeExtension/assets/104079404/d0de42be-7189-4b68-b2d0-67b9d5feafc1)

**Comment by dario-zubovic** [comment]
I've had this issue recently after fresh install of the extension. Turns out I was just on a bad connection and .NET download was failing. When I allowed it to download, Yarn extension started working normally, including graph view.
