### ISSUE TITLE
Unexpected "[" while reading a shortcut option statement

### ISSUE THREAD

**Issue by andresmakesgames** [YarnSpinnerTool/VSCodeExtension#46]
**What is the current behavior?**

I have options in my Yarn writeup that follow the expected escape pattern for special characters, e.g.
"->\[Wisdom\] Say something wise."
The graph in VS Code renders correctly, and the Yarn file runs correctly through my parsers and runners, but VS Code shows the following parse errors file in my Problems view:
`Unexpected "[" while reading a shortcut option statement`

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

This is the minimum yarn file I need in order to reproduce:
```
title: Node
position: 113,134
---
->\[Wisdom\] Say something wise.
===
```

**What is the expected behavior?**

As this is documented as the correct way to escape special characters, I would expect no Problems to be reported.

**Please tell us about your environment:**

Yarn Spinner prerelease v2.2.135
VS Code Insiders 1.84.0
MacOS Sonoma (14.0)

**Other information** 

N/A

**Comment by desplesda** [comment]
Reproduced this issue locally. The issue doesn't appear when any other non-blank character begins the line. The issue appears in both options and in regular lines.

**Comment by McJones** [comment]
Closing this as the core issue has been fixed, next update to VSCode should include this
